# Generated by Django 6.0.2 on 2026-02-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
